export const GET_FILMS = "GET_FILMS";
export const GET_FILM_BY_ID = "GET_FILM_BY_ID";
export const GET_BANNERS = "GET_BANNERS";
export const TOGGLE_TRAILER = "TOGGLE_TRAILER";
export const GET_FILMS_OF_CINEMA = "GET_FILMS_OF_CINEMA";
export const GET_SCHEDULE_OF_FILM = "GET_SCHEDULE_OF_FILM";
